package oop.Exception;

import java.util.Scanner;

/**
 * Created by RENT on 2017-07-25.
 */
/*
public class Program {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int[] arr = new int[]{10, 20, 30, 40, 50};

        System.out.println("Podaj elementy które chcesz wyświetlić");
        int numer = sc.nextInt();
        int wynik = 0;
        try {
            System.out.println("Zamierzam wykonac potencjalnie niebezpieczny kod");
            wynik = arr[numer];
            System.out.println("Udało się wykonac ten kod");
        } catch (ArrayIndexOutOfBoundsException ex) {

            System.out.println("Wyjątek");
            System.out.println(ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Wystąpil ogółny wyjątek " + ex.getMessage());
        } finally {
            System.out.println("Jestem w bloku finally - wykonujemu porzadki");
        }
        System.out.println("Twój element to: " + arr[numer]);
        System.out.println("numer");
        System.out.println("Koniec programu");
    }
}
*/
